apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityserver4auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityserver4auth
  template:
    metadata:
      labels:
        app: identityserver4auth
    spec:
      containers:
      - name: identityserver4auth-container
        image: identityserver4auth:latest  # Especifica la imagen aquí
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: identityserver4auth-service
spec:
  type: NodePort
  selector:
    app: identityserver4auth  # Debe coincidir con los labels del Deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
